const dogBreeds = [
  "Affenpinscher",
  "Akita",
  "Alpine Spaniel",
  "American Bulldog",
  "Ariegeois",
  "Beagle",
  "Bloodhound",
  "Boxer",
  "Briard",
  "Bulldog",
  "Chihuahua",
  "Drever",
  "German Shepherd",
  "Golden Retriever",
  "Great Dane",
  "Greyhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Kerry Beagle",
  "Maltese",
  "Otterhound",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Russell Terrier",
  "Serbian Hound",
  "Siberian Husky",
  "South Russian Ovcharka",
  "Southern Hound",
  "Spanish Water Dog",
  "Taigan",
  "Transylvanian Hound",
  "White Shepherd",
];

export default dogBreeds;
